name: build app
on:
  push:
    branches:
      - main
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cd app && yarn install && yarn run build
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cd server && yarn install && npx -y tsc
  test-docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build containers
      run: docker build .